title: Pegasus

collections:
  overview:
    output: true
    layout: page 
    permalink: /:collection/:path
  clients:
    output: true
    layout: page 
    permalink: /:collection/:path
  api:
    output: true
    layout: page 
    permalink: /:collection/:path
  administration:
    output: true
    layout: page 
    permalink: /:collection/:path
  blogs:
    output: true
    permalink: /:collection/:path
  community:
    output: true
    permalink: /:collection/:path

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - kramdown
  - rouge

defaults:
  -
    scope:
      path: ""
    values:
      show_sidebar: false
      toc: true
      front: false
  -
    scope:
      path: ""
      type: posts
    values:
      show_sidebar: false
      toc: true
      front: false
      layout: post
      header_style: is-dark
      hero_style: is-small is-light
